--------------------------------------------------------------------------------
-- This VHDL file is generated by EASE/HDL from TRANSLOGIC BV,
-- the 'Graphical Systems Design Tool'.
--
-- Ease 5.1 Revision 17.
-- Design library : TP2_TD3.
-- Host name      : Portable_Toto.
-- User name      : Thomas.
-- Time stamp     : Sun May 23 00:11:17 2004.
--
-- Designed by    : 
-- Company        : Translogic.
-- Design info    : 
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- Entity declaration of 'tb_MyFour'.
-- Last modified : Sun May 23 00:11:17 2004.
--------------------------------------------------------------------------------


library ieee, std ;
use ieee.std_logic_1164.all ;
use ieee.numeric_std.all ;

entity tb_MyFour is
end entity tb_MyFour ;

--------------------------------------------------------------------------------
-- Architecture 'a0' of 'tb_MyFour'
-- Last modified : Sun May 23 00:11:17 2004.
--------------------------------------------------------------------------------

architecture a0 of tb_MyFour is

constant Period : time := 50 ns;

type Start_t is (Grill,MicroWave,Cooker,Defrost);  
signal Start : Start_t ;

signal Timing : natural range 0 to 2**16-1;

  component MyFour
    port(
      Clock          : in     std_logic ; -- Clock
      DoorSensor     : in     std_logic ;
      Duration       : in     std_logic_vector(15 downto 0) ;
      G_Engine       : out    std_logic ;
      HeatSetting    : in     std_logic_vector(0 to 2) ;
      MW_Engine      : out    std_logic ;
      MicroWavePower : out    std_logic_vector(0 to 1) ;
      Plate_Engine   : out    std_logic ;
      Ring           : out    std_logic ;
      StartCooker    : in     std_logic ;
      StartDefrost   : in     std_logic ;
      StartGrill     : in     std_logic ;
      StartMicroWave : in     std_logic ;
      StopOp         : in     std_logic ;
      StopPlate      : in     std_logic ;
      Thermostat     : out    std_logic_vector(0 to 2) ;
      TimeDisplay    : out    std_logic_vector(15 downto 0) ;
      nReset         : in     std_logic ) ; -- Reset
  end component MyFour ;
  signal StopOp         :  std_logic ;
  signal DoorSensor     :  std_logic ;
  signal StopPlate      :  std_logic ;
  signal Duration       :  std_logic_vector(15 downto 0) ;
  signal HeatSetting    :  std_logic_vector(0 to 2) ;
  signal Plate_Engine   :  std_logic ;
  signal Ring           :  std_logic ;
  signal G_Engine       :  std_logic ;
  signal MW_Engine      :  std_logic ;
  signal TimeDisplay    :  std_logic_vector(15 downto 0) ;
  signal Thermostat     :  std_logic_vector(0 to 2) ;
  signal MicroWavePower :  std_logic_vector(0 to 1) ;
  signal nReset         :  std_logic := '0' ;
  signal Clock          :  std_logic := '0' ;
  signal start_vec      :  std_logic_vector(0 to 3) ;
begin


  DUT: MyFour
    port map(
      Clock => Clock,
      DoorSensor => DoorSensor,
      Duration => Duration,
      G_Engine => G_Engine,
      HeatSetting => HeatSetting,
      MW_Engine => MW_Engine,
      MicroWavePower => MicroWavePower,
      Plate_Engine => Plate_Engine,
      Ring => Ring,
      StartCooker => start_vec(2),
      StartDefrost => start_vec(3),
      StartGrill => start_vec(0),
      StartMicroWave => start_vec(1),
      StopOp => StopOp,
      StopPlate => StopPlate,
      Thermostat => Thermostat,
      TimeDisplay => TimeDisplay,
      nReset => nReset ) ;


  Stimuli: process		-- EASE/HDL sens.list
  begin

    Duration         <= (others => '0');
    StopPlate        <= '0';
    DoorSensor       <= '0';
    StopOp           <= '0';
    start_vec        <= (others => '0');
    HeatSetting      <= (others => '0');
  
    wait until nReset = '1';
  
    for i in start_vec'range loop
  
      wait for 500 ns;
      start_vec(i) <= '1';
      Duration <= (others => '0');
      Duration(i+2) <= '1';
      HeatSetting <= std_logic_vector(to_unsigned(i,HeatSetting'length));
      wait until Clock= '1';
      start_vec <= (others => '0');
      HeatSetting <= (others => '0');
  
      wait until Ring = '1' for 3 ms;
  
      wait for 500 ns;
      start_vec(i) <= '1';
      Duration <= (others => '0');
      Duration(i+2) <= '1';
      HeatSetting <= std_logic_vector(to_unsigned(i,HeatSetting'length));
      wait until Clock= '1';
      start_vec  <= (others => '0');
      HeatSetting <= (others => '0');
  
      wait until Ring = '1';
  
    end loop;
  
    wait;

  end process Stimuli ;

  nReset <= '0', '1' after 100 us;
  Clock <= not Clock after Period/2;


end architecture a0 ; -- of tb_MyFour

