#ifndef _CDEV_ECHO_H
#define _CDEV_ECHO_H

#define CDEV_ECHO_IOCTL_MAGIC 't'
#define CDEV_ECHO_IOCTL_RESET     _IO(CDEV_ECHO_IOCTL_MAGIC, 0xA0)
#define CDEV_ECHO_IOCTL_SET_MODE  _IOW(CDEV_ECHO_IOCTL_MAGIC, 0xA1, unsigned char)
#define CDEV_ECHO_IOCTL_GET_MODE  _IOR(CDEV_ECHO_IOCTL_MAGIC, 0xA2, unsigned char)

#define CDEV_ECHO_MODE_DEFAULT 0
#define CDEV_ECHO_MODE_LOWER   1
#define CDEV_ECHO_MODE_UPPER   2

#endif
